-- 1. Create the Curated Items table
CREATE TABLE IF NOT EXISTS public.curated_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category text NOT null, -- 'dsocials' | 'dgames' | 'prediction'
  title text NOT null,
  description text NOT null,
  url text NOT null,
  icon_url text, -- Logo image URL (optional)
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT null
);

-- Disable Row Level Security (RLS) so that the mobile apps can read items anonymously
ALTER TABLE public.curated_items DISABLE ROW LEVEL SECURITY;

-- 2. Create the Admin Profiles table for role/permission management
CREATE TABLE IF NOT EXISTS public.admin_profiles (
  id uuid REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  email text NOT null UNIQUE,
  role text NOT null DEFAULT 'sub_admin', -- 'super_admin' | 'sub_admin'
  permissions text[] NOT null DEFAULT '{}', -- e.g., '{"dsocials", "dgames", "prediction"}'
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT null
);

ALTER TABLE public.admin_profiles DISABLE ROW LEVEL SECURITY;

-- 3. Insert some default curated data to populate the app screens immediately
INSERT INTO public.curated_items (category, title, description, url, icon_url)
VALUES 
  ('dgames', 'PancakeSwap Games', 'Play decentralized mini-games and stake assets directly inside PancakeSwap.', 'https://pancakeswap.finance/gaming', 'https://assets.coingecko.com/coins/images/12632/large/pancakeswap-cake-logo.png'),
  ('dgames', 'Uniswap Portal', 'Interact with swap tournaments and secondary liquidity pools.', 'https://app.uniswap.org', 'https://assets.coingecko.com/coins/images/12504/large/uniswap-uni.png'),
  ('dsocials', 'Lenster (Lens Protocol)', 'A decentralized, permissionless social media platform built on Lens.', 'https://lens.xyz', 'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xDb46d1Dc155D524676157EFaC1B11c1e54F9D13E/logo.png'),
  ('dsocials', 'Farcaster Warpcast', 'Connect with developers and creators on the Farcaster decentralized social graph.', 'https://warpcast.com', 'https://assets.coingecko.com/coins/images/35072/large/farcaster.png'),
  ('prediction', 'Polymarket', 'The world''s largest decentralized information and prediction market platform.', 'https://polymarket.com', 'https://assets.coingecko.com/coins/images/33022/large/polymarket.png')
ON CONFLICT DO NOTHING;
